version: 2.1

jobs:
  job_a:
    docker:
      - image: cimg/base:2023.03
    steps:
      - run: echo "this is A"
  job_b:
    docker:
      - image: cimg/base:2023.03
    steps:
      - run: echo "this is B"
  job_c:
    docker:
      - image: cimg/base:2023.03
    steps:
      - run: echo "this is C"

workflows:
  deploy:
    jobs:
      - job_a
      - job_b
      - job_c 
